### PR TITLE
Layout refactoring

### PR DESCRIPTION
**Pull request by andrewgdotcom**
Factor out keymap layers into separate files to aid mixing and matching customisations

### CODE REVIEW

**Comment by andrewgdotcom** [comment]
Re #19. This change allows layers to be distributed as individual include files and marshalled into a layer stack usimg a comparatively simple config file.

**Comment by obra** [comment]
Understood. I want to think carefully about this, as it's going to affect
the docs. I suspect we may want to end up with two "standard" firmware
codebases. One that matches, as closely as possible, what we ship on the
hardware and one that's optimized for messing around.

**Comment by algernon** [comment]
I second the two firmware idea - we could perhaps include some extra stuff in the second that makes messing around easier (thinking about Focus & EEPROM-Keymap here). O:)

**Comment by andrewgdotcom** [comment]
Considering that @obra has already expanded the sketch to include optional layer definitions, is this worth revisiting? At the very least I think we should put layouts and module definitions in separate files...

**Comment by obra** [comment]
Yes, it's 100% worth reviewing and improving.

I do think that -some- layouts should be in the default sketch (QWERTY and
the user's custom sketch), since that's 99% of what most folks will ever
look at. But I'd love to improve things for everybody else, too.
ᐧ

**Comment by andrewgdotcom** [comment]
I'm happy to trash this PR and start again, if there is an agreed plan. The first step (and most important for me) would be to break out the current layout definitions from master into a standalone but monolithic `keymaps.h` file, leaving the rest of the logic untouched. We can come back to the question of which keymaps should be included (and how) in another ticket. Would this be OK?

**Comment by algernon** [comment]
I like the idea of a separate `keymaps.h` file, makes it easier to navigate the main sketch too.

**Comment by andrewgdotcom** [comment]
OK, I'll close this because the branch has diverged too much and open another issue. Will link here.

**Pull request closed without merging**
