### PR TITLE
Improve usability

### PR DESCRIPTION
**Pull request by TheBaronHimself**
This pull request aims to add convenience to the process of downloading the firmware and dependencies, keeping them up to date, building and flashing, and customisation.

To that end, `make setup` and `make update` are introduced:

* `make setup` downloads the newest versions of required Arduino boards and external plugins (declared in `external_sources.txt`) automatically and stores them locally.

* `make update` updates all resources automatically to their latest versions.

The sketch file has been moved to the `src` directory so users who may wish to split up their configuration can do so directly there.

Lastly, references to required libraries and board definitions in the `Makefile` have been changed to local sources, which should resolve issues relating to hardware and board paths users have reported in the past.

Note: This has only been tested on macOS, however, it should work just as well on Linux.

### CODE REVIEW

**Comment by TheBaronHimself** [comment]
The fact that the travis check failed isn't surprising to me. I didn't want to mess with the configuration of the automated test.

**Comment by TheBaronHimself** [comment]
I realise that having moved the ino to `src` might be an issue in that it may go against the Arduino IDE library specification. If the rest suits, that would be an easy fix, though

**Comment by obra** [comment]
In general, I prefer one logical change per pull request. It makes it a lot easier to review and apply each different bit.

I'm not going to take the move of the script to src for the 'default' simple firmware.
I'd prefer that the makefile targets stay in the makefile rather than in a bash script.

The patterns of having the user clone kaleidoscope and plugins inside their repo is a pattern I want to specifically discourage, especially for novice users who we want to encourage to install Kaleidoscope and the board support via the Arduino boards manager.

The EXTERNAL_SOURCES thing is...a little funny. It's another implementation of something like either checking in libraries or using git submodules, which feels like it's more confusion than it's worth. (Also, I'd probably not make a config file that's evaluated as a shell script a .txt file. but that's neither here nor there.)

**Comment by TheBaronHimself** [comment]
It just occurred to me that I confused the idea of having an easy-to-use sketch repo template with editing the actual firmware repo. Structurally, the latter looks quite similar to what I've set up for myself based on @algernon's sketch repo. Effectively my changes lead to the firmware cloning a copy of itself into itself, which doesn't make much sense. I shall set up a separate repo for the template I aimed to create in the first place :).

**Pull request closed without merging**
