### PR TITLE
Adapted the sketch to changes in the Key API

### PR DESCRIPTION
**Pull request by noseglasses**
This PR adapts the firmware to https://github.com/keyboardio/Kaleidoscope/pull/720. Only merge after #720 has been merged.

Signed-off-by: Florian Fleissner <florian.fleissner@inpartik.de>

### CODE REVIEW

**Comment by noseglasses** [comment]
@algernon, Travis failed on this PR because the union->class PR was not yet merged.
It would be good to merge this soon as currently the default firmware throws ugly deprecation warnings.

**Comment by algernon** [comment]
Yeah, I'll merge soon.

**Comment by emlun** [comment]
How do I build this? I have `./Model01-Firmware` checked out at commit 2f9d140ba94d6c5934ad17eed98654211706c7a7 (current master) and `./hardware/keyboardio/avr/libraries/Kaleidoscope` checked out at commit [d41398dd](https://github.com/keyboardio/Kaleidoscope/commit/d41398dd220cd27065be9def696deeb71d4e2988) (also current master), but both `make` and `make flash` in `Model01-Firmware` give me:

```
~/Arduino/Model01-Firmware (master) $ make
BOARD_HARDWARE_PATH="/home/emlun/Arduino/hardware" /home/emlun/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope/bin//kaleidoscope-builder build-all
Building ./Model01-Firmware 0.0.0-gv1.22-69-g2f9d into /tmp/kaleidoscope-emlun/sketch/19630589-Model01-Firmware.ino/output...
/home/emlun/Arduino/Model01-Firmware/Model01-Firmware.ino: In function 'void anyKeyMacro(uint8_t)':
/home/emlun/Arduino/Model01-Firmware/Model01-Firmware.ino:308:13: error: 'Key {aka union kaleidoscope::Key}' has no member named 'setKeyCode'
     lastKey.setKeyCode(Key_A.getKeyCode() + (uint8_t)(millis() % 36));
             ^~~~~~~~~~
/home/emlun/Arduino/Model01-Firmware/Model01-Firmware.ino:308:30: error: 'Key {aka union kaleidoscope::Key}' has no member named 'getKeyCode'
     lastKey.setKeyCode(Key_A.getKeyCode() + (uint8_t)(millis() % 36));
                              ^~~~~~~~~~
exit status 1
make: *** [/home/emlun/Arduino/hardware/keyboardio/build-tools/makefiles//rules.mk:80: build-all] Error 1
```

The methods do exist in the `key_defs.h` in the Kaleidoscope submodule... so why does this not work? If I instead check `Model01-Firmware` out to commit 4299824b114a001fd74ae790669ff0d39563d62d, then it compiles and flashes successfully.

**Comment by emlun** [comment]
Ah, turns out the build was picking up a Kaleidoscope from `~/.arduino15/packages/keyboardio` instead of the sibling repository. Never mind me!

**Pull request merged**
