### PR TITLE
Make the pointer to the wiki LOUD

### PR DESCRIPTION
**Pull request by Jennigma**
We just had a new person who found the forums but didn't see the note to use the wiki at the top of this file. I'm making it louder. :-)

### CODE REVIEW

**Comment by tmalsburg** [comment]
Hm, that wouldn't have solved my problem. I actually did see the link to the wiki, but there is a lot of material in the wiki and while the landing page explains that layouts can be changed, the relevant section does not point to the documentation describing how.

**Comment by Jennigma** [comment]
I'm working on a new landing page here:

https://github.com/keyboardio/Kaleidoscope/wiki/New-Home

so I'm somewhat anticipating a clearer set of paths for folks with different interest levels to follow. There will be bulleted jump points below the images, and the titles will lead to introductory pages. I'm writing up the interstitial text and such so I can (hopefully) push it live today.

**Comment by tmalsburg** [comment]
Fantastic.  I think this is going to go a long way in helping new users get oriented.  Thank you.

**Comment by obra** [comment]
Thanks. Applied

**Comment by Jennigma** [comment]
@tmalsburg would you do me a favor and re-read the intro to see if it gives you a better grounding? I revised it over the weekend and added a lot more detail:

https://github.com/keyboardio/Kaleidoscope/wiki/Keyboardio-Model-01-Introduction

**Comment by tmalsburg** [comment]
I only had time for a quick look but this looks fantastic.  Thank you very much!  I will report in more detail when I worked through this.

**Pull request merged**
